{"name": "test_get_use_by_id", "status": "skipped", "statusDetails": {"message": "XFAIL this test is expecting failure\n\nAssertionError: assert 404 == <HTTPStatus.OK: 200>\n +  where 404 = <Response [404]>.status_code\n +  and   <HTTPStatus.OK: 200> = HTTPStatus.OK", "trace": "@pytest.mark.xfail(condition=lambda: True, reason='this test is expecting failure')\n    def test_get_use_by_id():\n        response = UsersAPI().get_user_by_id(6562)\n>       assert response.status_code == HTTPStatus.OK\nE       assert 404 == <HTTPStatus.OK: 200>\nE        +  where 404 = <Response [404]>.status_code\nE        +  and   <HTTPStatus.OK: 200> = HTTPStatus.OK\n\nhw_13\\tests\\api_tests\\test_api_users.py:16: AssertionError"}, "steps": [{"name": "get_user_by_id", "status": "passed", "parameters": [{"name": "user_id", "value": "6562"}, {"name": "headers", "value": "None"}], "start": 1670162753464, "stop": 1670162757901}], "start": 1670162753464, "stop": 1670162757901, "uuid": "33dac4c0-6118-4d7a-b75b-fa3f75926746", "historyId": "ea88d4de2e0046968c1867d2241a9e67", "testCaseId": "37920e13a9c21a2ab1386ee31ccc2331", "fullName": "hw_13.tests.api_tests.test_api_users#test_get_use_by_id", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(condition=<function <lambda> at 0x000001ECE3B3C430>, reason='this test is expecting failure')"}, {"name": "parentSuite", "value": "hw_13.tests.api_tests"}, {"name": "suite", "value": "test_api_users"}, {"name": "host", "value": "DESKTOP-YEVHEN"}, {"name": "thread", "value": "12888-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "hw_13.tests.api_tests.test_api_users"}]}